FROM scratch
# https://raw.githubusercontent.com/CentOS/sig-cloud-instance-images/7c2e214edced0b2f22e663ab4175a80fc93acaa9/docker/centos-7-docker.tar.xz
ADD centos-7-docker.tar.xz /

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="CentOS Base Image" \
    org.label-schema.vendor="CentOS" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20181204"

CMD ["/bin/bash"]

